
services:
  postgres:
    image: postgres:16
    container_name: aruba-postgres
    environment:
      POSTGRES_DB: aruba_monitoring
      POSTGRES_USER: aruba
      POSTGRES_PASSWORD: aruba
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: aruba-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pgdata:
