server:
  port: 8081
spring:
  application:
    name: aruba-business-monitoring
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aruba_monitoring}
    username: ${SPRING_DATASOURCE_USERNAME:aruba}
    password: ${SPRING_DATASOURCE_PASSWORD:aruba}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:sql/schema.sql
  RabbitMQ:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2.0
        default-requeue-rejected: false
