server:
  port: 8080
spring:
  application:
    name: aruba-business-monitoring
  servlet:
    multpart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: aruba
    password: aruba
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  sql:
    init:
      mode: never
  RabbitMQ:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
          multiplier: 2.0
        default-requeue-rejected: false
